# Use root/example as user/password credentials
version: '3.1'

services:

  node:
    image: "node:8"
    user: "node"
    working_dir: /usr/source/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/usr/source/app
    expose:
      - "8081"
    command: "npm start"

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example